### ISSUE TITLE
Tagged version run with latest image

### ISSUE THREAD

**Issue by tyx** [OskarStark/phpstan-ga#28]
Hello !

It seems using a tagged version of this github action has no effet, and still run the latest docker image:

See
https://github.com/async-aws/aws/runs/749139572?check_suite_focus=true#step:5:1

https://github.com/async-aws/aws/runs/749139572?check_suite_focus=true#step:2:70

maybe we should also update the action.yml by specifying the docker image tag to use?

**Comment by tyx** [comment]
Or even better, why not using same system that setup-php GA : https://github.com/marketplace/actions/setup-php-action#php-version-required

by letting user inject the required phpstan version. And you no longer need to publish a new GithubAction version for each release, just the new Docker image.

**Comment by OskarStark** [comment]
You mean if no version is provided, use the latest one and if one is provided, use this?

Make sense. Open for a PR?

**Comment by shouze** [comment]
In fact, it should be important to not mix up action versioning and phpstan versioning.

So, more something like that (if it works, not tested):
```yml
# https://help.github.com/en/articles/metadata-syntax-for-github-actions

author: 'OskarStark'

branding:
    icon: 'check'
    color: 'blue'

description: 'Use PHPStan via GithubAction.'

name: 'OSKAR-phpstan'

inputs:
  version:
    description: phpstan version, defaults to latest
    required: false
    default: latest

runs:
    using: 'docker'
    image: 'docker://oskarstark/phpstan-ga:${{ inputs.version }}'
```
