### ISSUE TITLE
trigger_error is causing an error

### ISSUE THREAD

**Issue by garak** [OskarStark/phpstan-ga#47]
I have a file with a line like the following

```php
<?php
@\trigger_error('an error...', \E_USER_DEPRECATED);
```

Such file causes no errors in my local run of phpstan (version 0.12.90, the latest so far, with clean cache).
When my GitHub action is run, instead, that line is causing an error (and the action fails).

This is the job definition:
```yaml
phpstan:
    runs-on: ubuntu-20.04
    name: PHPStan
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: PHPStan
          uses: docker://oskarstark/phpstan-ga
          env:
              REQUIRE_DEV: true
          with:
              args: analyse
```
