### ISSUE TITLE
entrypoint.sh: line 26: syntax error: bad substitution

### ISSUE THREAD

**Issue by Wipster** [OskarStark/phpstan-ga#68]
Since the last Update 1.10.0 I'm getting this error:
```
PHPStan - PHP Static Analysis Tool 1.10.45
Installed PHPStan extensions
  No dependencies installed. Try running composer install or update.
/entrypoint.sh: line 26: syntax error: bad substitution
```

Makes me wonder as line 26 doesn't contain any code: https://github.com/OskarStark/phpstan-ga/blob/master/entrypoint.sh

I tried downgrading like this in my yml file:
`uses: docker://oskarstark/phpstan-ga@1.9.0`

It failed because the docker image can't be pulled:
```
Pull down action image 'oskarstark/phpstan-ga@1.9.0'
Error: Docker pull failed with exit code 1
```

I also tried different ubuntu versions as I thought it could be that sh doesn't point to bash anymore, but it didn't help. Thanks for your awesome work anyway 🙂👍

Here is the full action setup:

```
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-  

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        env:
          CHECK_PLATFORM_REQUIREMENTS: false
          REQUIRE_DEV: true
        with:
          args: analyse packages/ --level 8
    timeout-minutes: 20
```

When removing The PHP setup and cache steps it yields the same error:

```
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        env:
          CHECK_PLATFORM_REQUIREMENTS: false
          REQUIRE_DEV: true
        with:
          args: analyse packages/ --level 8
    timeout-minutes: 20
```
