### ISSUE TITLE
php extensions

### ISSUE THREAD

**Issue by staabm** [OskarStark/phpstan-ga#9]
I started playing with this action today and pretty quickly run into a 'dead end' as far as php extension based sources is concerned.

the check errors because the php-docker container does not contain the required php extensions (or at least they are not loaded/configured):

![image](https://user-images.githubusercontent.com/120441/63459341-a8373c80-c454-11e9-84a9-f73f213cd638.png)

would it be possible to e.g. use a docker container which contains the most used/popular php extensions (or maybe those which are bundled with ubuntu by default or similar)

**Comment by OskarStark** [comment]
Sure can you list exactly which are missing ?

**Comment by staabm** [comment]
for my first example project it misses: apc/apcu, memcache, memcached

**Comment by staabm** [comment]
See https://github.com/OskarStark/phpstan-ga/issues/11#issuecomment-538725062 for my current way to handle extensions

**Comment by sagikazarmark** [comment]
If those extensions are required by Composer, but not for the PHPStan check I would do the following:

Install dependencies separately:

```
      - name: Install
        uses: docker://composer
        with:
          args: install --ignore-platform-reqs
```

Add an environment variable, like `COMPOSER_INSTALL=0` to the entrypoint.

As a workaround, you can override the entrypoint of the phpstan check:

```
#!/bin/sh -l

sh -c "composer install --no-scripts --no-progress --ignore-platform-reqs --quiet && /composer/vendor/bin/phpstan $*"
```

```
      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          entrypoint: ./.github/workflows/phpstan.entrypoint
          args: analyze --no-progress
```
